version: '3.7'

services:
    mongodb:
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        volumes:
            - type: volume
              source: mongodb_data_volume
              target: /data/db

volumes:
    mongodb_data_volume: